# A taster - making your first map  {#taster} 

This chapter shows the steps through an example process of map-making. It demonstrates the focus and potential of this book, so that the readers can quickly see what this book aims to achieve and how it is done. 


```{r, c2-packages, results='hide', warning=FALSE, message=FALSE, include = FALSE, eval=FALSE}
#Install packages
cran_packages_to_install <- c(
  "ggplot" ,           # plot-making package
  "tmap",              # map-making package for static and interactive maps
  "tidyverse",         # metapackage containing dplyr, ggplot2 and other packages
  "sf",                # package for working with spatial data
  "s2",                # package for working with spatial data
  "rnaturalearth",     # data package
  "rnaturalearthdata", # data package
  "afrilearndata",     # datapackage
  "tmaptools",         # map building package
  "raster"
  )

install.packages(cran_packages_to_install)
```

```{r, c2-libraries, results='hide', warning=FALSE, message=FALSE, include = FALSE}
#Load packages
library(tmap)
library(ggplot2)
library(sf)
library(s2)
library(afrilearndata)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(tmaptools)
library(raster) 
```

```{r c2-dataset, include=FALSE}
#static mode activated
tmap_mode("plot")

#create dataset
africa <- ne_countries(continent = 'africa', scale = "medium", returnclass = "sf")
```

## Simple maps
```{r c2-simple-map}

sf_use_s2(FALSE) #switches off spherical geometry, needed after sf package update


tm_shape(africountries) +
    tm_polygons()

map_2 = tm_shape(africountries) +
    tm_polygons(col = "pop_est", title = "Population")

map_3 = map_1 +
  tm_shape(afrihighway) +
    tm_lines(col = "blue")

tmap_arrange(map_1, map_2, map_3)

```

## Static maps
```{r c2-empty-static-map1,message=FALSE, fig.cap = "Examples of maps"}

# #Create an empty map of Africa using a classic style
# map_basic = tm_style("classic")+
# tm_shape(africa)+
#  tm_polygons()+
#   tm_layout(title = "Africa", title.position = c("center", "top"), 
#             inner.margins = 0.05, legend.text.size = 0.47)
# 
# #Add points for medium airports
# data(afriairports)
# m_airports = afriairports %>% filter(type == "medium_airport")
# 
# map_points = map_basic +
#   tm_shape(m_airports)+
#     tm_dots(col = "type", palette="blue", 
#             labels = "Medium airports", title = "")+
#       tm_legend(legend.position = c("left", "bottom")) +
#         tm_layout(scale = 1.07)
# 
# 
# #Add bubbles with population and GDP size
# map_bubbles = map_points +
#        tm_shape(africa)+
#           tm_bubbles(size = "pop_est", col = "income_grp", title.col = "Income level",
#               title.size = "Population", 
#               labels = c("High", "Upper middle", "Lower middle", "Lower"))
# 
# 
# tmap_arrange(map_basic, map_points, map_bubbles)

```

```{r c2-empty-static-map2, warning = FALSE, message=FALSE, fig.cap = "Examples of maps 2"}

# #Basic map 2
# map_basic_2 = tm_style("watercolor")+
#   tm_shape(africa)+
#       tm_fill(col = "pop_est", style = "jenks", title = "Population")+
#         tm_layout(title = "Africa", 
#                   title.position = c("center", "top"), legend.text.size = 0.50)
#   
# #Add highways names
# map_highways = map_basic_2 +
#   tm_shape(afrihighway)+
#               tm_lines(col = "black")
# 
# #Add country names
# map_named = map_highways +
#   tm_shape(africapitals)+
#       tm_dots(col = "red", border.col = "black")+ 
#           tm_text("capitalname",  size = 0.35)
# 
# 
# tmap_arrange(map_basic_2, map_highways, map_named)

```

## Interactive maps
```{r c2-interactive_map, fig.show="hold", out.width="50%"}
# tmap_mode("view") 
# 
# breaks=c(0,2,20,200,2000,25000)
# 
# tm_shape(afripop2020) +
#     tm_raster(breaks=breaks, title = "Population per km sq") +
# tm_shape(afrihighway) +
#     tm_lines(col = "blue") + 
# tm_shape(africapitals) +
#     tm_dots(col = "black", alpha=0.5)
```