# Visualising spatial data part 1: sf, mapview, tmap {#visualising-1}

In this section we will learn:

1. How to create a static map 
    + Filled with colours based on the categorical variable
    + Filled with colours based on the continuous variable
2. How to create an ordered and unordered list

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
**Hint**: In order to work properly a list requires an empty line beforehand.
</div>

## tmap package
### Basics (this step can be removed if the basic steps can be put in ch.3 'R recap', since they repeat for all packages)
Set up the working directory 
```{}
setwd("path to your directory")
```

Install required packages

```{}
install.packages(c("ggplot2","sf", "rnaturalearth", "rnaturalearthdata"))
```

Load the packages

```{}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
```
Create a dataset
```{}
africa <- ne_countries(continent = 'africa', scale = "medium", returnclass = "sf")
```
### Static maps
Map with colour fill based on the continuous variable
```{}
ggplot(africa) + 
  geom_sf(aes(fill=lastcensus)) + 
  coord_sf(datum = NA) + 
  labs(fill = "Last census") +
  theme_minimal()
```

Crate a categorical variable
```{}
africa <- africa %>%
  mutate(cuts = case_when(
    lastcensus <= 1970 ~ "1970 or earlier",
    lastcensus > 1970 & lastcensus <= 2002 ~ "between 1970 and 2002",
    lastcensus > 2002 & lastcensus <= 2008 ~ "between 2002 and 2008",
    lastcensus > 2008 & lastcensus <= 2010 ~ "between 2008 and 2010",
    lastcensus > 2010 & lastcensus <= 2012 ~ "between 2010 and 2012"))
```
Map with colour fill based on the categorical variable
```{}
ggplot(africa) + 
  geom_sf(aes(fill=cuts)) + 
  coord_sf(datum = NA) + 
  theme_minimal() +
  labs(fill = "Last census") +
  scale_fill_manual(values = c("red4", "red1", "tomato1", "gold","darkolivegreen2"))
```
### Layers
### Interactive maps

## sf package 

## mapview package
Mapview package allows for an interactive viewing of spatial objects in R.

